[package]
name = "reitunes"
description = "Reilly Wood's personal music library, Rust edition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reitunes-workspace = { path = ".." }
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
clap.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
r2d2.workspace = true
r2d2_sqlite.workspace = true
rusqlite.workspace = true
mime_guess.workspace = true
dirs.workspace = true
axum = { version = "0.8.3", features = ["ws"] }
axum-extra = { version = "0.10.1", features = ["multipart"] }
askama = {version = "0.13.0", features = ["serde_json"]  }
rig-core = { version = "0.31.0", features = ["derive"] }
vite-rs = "0.2"
vite-rs-axum-0-8 = "0.2"
tower-cookies = "0.11.0"
axum-macros = "0.5.0"
openssl = { version = "0.10.72", features = ["vendored"] }
thiserror = "1.0"
regex = "1.10"
schemars = "1.0"
lofty = "0.22"
tempfile = "3.0"
aws-sdk-s3 = "1.76"
aws-config = "1.6"
urlencoding = "2.1"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
jiff.workspace = true
indexmap.workspace = true
rand.workspace = true
sha2.workspace = true
base64 = "0.22"

[dev-dependencies]
pretty_assertions = "1.4.1"
