# switching back to bash for now
# set shell := ["nu", "-c"]

run-with-secrets:
    #!/usr/bin/env bash
    set -euo pipefail
    set -a && source ./prod.env && set +a
    cargo run

build-with-secrets:
    #!/usr/bin/env bash
    set -euo pipefail
    set -a && source ./prod.env && set +a
    cargo build --release

run:
    cargo run

test:
    cargo nextest run

watch-tests:
    watchexec --exts=rs,sql,html -- cargo nextest run

expected_filename := if os_family() == "windows" { "sonos-player.exe" } else { "sonos-player" }

build-release:
    cargo build --release

publish-to-local-bin: build-with-secrets
    cp ../target/release/{{expected_filename}} ~/bin/

build-linux-x64:
    cross build --target x86_64-unknown-linux-gnu --release

build-linux-arm64:
    cross build --target aarch64-unknown-linux-gnu --release
